(()=>{if(window.__EVOLVIAN_APP_V2__)return;window.__EVOLVIAN_APP_V2__=true;
const $=(s,r=document)=>r.querySelector(s),esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};
const toast=(message,bad=false)=>{let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=message;t.className='toast show'+(bad?' bad':'');clearTimeout(t._timer);t._timer=setTimeout(()=>t.className='toast',4500)};
const friendly=e=>{const m=String(e?.message||e||'Unknown error');if(/invalid login credentials/i.test(m))return'Email or password is incorrect.';if(/email not confirmed/i.test(m))return'Please confirm your email before signing in.';if(/user already registered|already registered/i.test(m))return'This email is already registered. Sign in instead.';if(/database error saving new user/i.test(m))return'Account creation could not finish. Please try again.';if(/rate limit|too many requests|only request this after/i.test(m))return'Please wait a minute before requesting another confirmation email.';if(/email link is invalid or has expired|one-time token not found/i.test(m))return'That confirmation link has expired or was already used. Request a new confirmation email.';if(/failed to fetch|networkerror|network request failed/i.test(m))return'Network connection failed. Check your internet connection and try again.';if(/timed out/i.test(m))return'The request took too long. Check your connection and try again.';return m};
const timeout=(promise,ms=15000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out.')),ms))]);
let sb=null;
function init(){if(sb)return true;try{if(!window.supabase||!window.Evolvian_CONFIG?.SUPABASE_URL||!window.Evolvian_CONFIG?.SUPABASE_PUBLISHABLE_KEY)throw new Error('Authentication service is not configured.');sb=window.supabase.createClient(window.Evolvian_CONFIG.SUPABASE_URL,window.Evolvian_CONFIG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.EvolvianAuth=sb;return true}catch(e){console.error(e);toast('Authentication service could not start. Refresh the page.',true);return false}}
async function getSession(){if(!sb)return null;try{const r=await timeout(sb.auth.getSession());if(r.error)throw r.error;return r.data?.session||null}catch(e){console.error('session',e);return null}}
async function getProfile(s){if(!sb||!s?.user?.id)return null;try{const r=await timeout(sb.from('profiles').select('*').eq('id',s.user.id).maybeSingle());if(r.error)throw r.error;return r.data||null}catch(e){console.error('profile read',e);return null}}
async function refreshIdentity(s){const current=s||await getSession();document.querySelectorAll('.avatar').forEach(a=>a.textContent='A');if(!current)return null;const p=await getProfile(current);const name=(p?.display_name||p?.username||current.user.email||'Member').trim();document.querySelectorAll('.avatar').forEach(a=>a.textContent=(name[0]||'M').toUpperCase());return p}
function busy(form,on,label){const b=form?.querySelector('button[type="submit"]');if(!b)return;b.disabled=on;b.dataset.original??=b.textContent;if(on)b.textContent=label;else b.textContent=b.dataset.original}
function bindAuth(){const login=$('#loginForm');if(login&&!login.dataset.bound){login.dataset.bound='1';login.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return toast('Authentication service is unavailable. Refresh and try again.',true);const email=login.elements.email.value.trim().toLowerCase(),password=login.elements.password.value;if(!email||!password)return toast('Enter your email and password.',true);busy(login,true,'Signing in…');try{const r=await timeout(sb.auth.signInWithPassword({email,password}));if(r.error)throw r.error;await refreshIdentity(r.data.session);toast('Signed in successfully');location.replace('index.html')}catch(err){console.error('login',err);toast(friendly(err),true);busy(login,false)}})}
const signup=$('#signupForm');if(signup&&!signup.dataset.bound){signup.dataset.bound='1';signup.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return toast('Authentication service is unavailable. Refresh and try again.',true);const name=signup.elements.displayName.value.trim()||'Member',email=signup.elements.email.value.trim().toLowerCase(),password=signup.elements.password.value;if(!email||!password)return toast('Enter your email and password.',true);if(name.length>80)return toast('Display name must be 80 characters or less.',true);if(password.length<6)return toast('Password must be at least 6 characters.',true);busy(signup,true,'Creating account…');try{const r=await timeout(sb.auth.signUp({email,password,options:{data:{name,display_name:name}}}));if(r.error)throw r.error;if(r.data?.session){await refreshIdentity(r.data.session);toast('Account created successfully');location.replace('profile.html')}else{busy(signup,false);signup.reset();toast('Account created. Check your email to confirm, then sign in.')}}catch(err){console.error('signup',err);toast(friendly(err),true);busy(signup,false)}})}}
async function authBoot(){const s=await getSession();if($('#loginForm')&&s){location.replace('index.html');return s}document.querySelectorAll('[data-signout]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',async()=>{b.disabled=true;try{const r=await timeout(sb.auth.signOut());if(r.error)throw r.error;location.replace('login.html')}catch(e){b.disabled=false;toast(friendly(e),true)}})});try{sb.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{if(event==='SIGNED_IN')refreshIdentity(session);if(event==='SIGNED_OUT')document.querySelectorAll('.avatar').forEach(a=>a.textContent='A')},0)})}catch(e){console.error('auth listener',e)}return s}
async function feed(){const el=$('#feed');if(!el||!sb)return;const r=await timeout(sb.from('posts').select('id,title,body,created_at,profiles!posts_author_id_fkey(display_name,level,community_position)').order('created_at',{ascending:false}).limit(30));if(r.error){console.error('feed',r.error);el.innerHTML='<p class="muted">Feed is temporarily unavailable. Please refresh.</p>';return}el.innerHTML=r.data?.length?r.data.map(p=>`<article class="post"><div class="posthead"><div class="mini">${esc((p.profiles?.display_name||'M')[0])}</div><div><b>${esc(p.profiles?.display_name||'Member')}</b><small>${esc((p.profiles?.level||'initiate').toUpperCase())} · ${esc((p.profiles?.community_position||'member').toUpperCase())}</small></div></div>${p.title?`<h2>${esc(p.title)}</h2>`:''}<p>${esc(p.body)}</p></article>`).join(''):'<p class="muted">No posts yet.</p>'}
async function post(){const form=$('#postForm');if(!form||!sb)return;form.addEventListener('submit',async e=>{e.preventDefault();const s=await getSession();if(!s){location.replace('login.html');return}const body=form.elements.body.value.trim(),title=form.elements.title.value.trim();if(!body)return toast('Write something before posting.',true);const r=await timeout(sb.from('posts').insert({author_id:s.user.id,type:'post',title:title||null,body}));if(r.error)return toast(friendly(r.error),true);form.reset();toast('Posted');await feed()})}
async function lists(){if(!sb)return;for(const [id,table,label] of [['courseList','courses','Course'],['courseLibrary','courses','Course'],['projectList','projects','Project'],['challengeList','challenges','Challenge']]){const el=$('#'+id);if(!el)continue;const r=await timeout(sb.from(table).select('*').order('created_at',{ascending:false}).limit(30));if(r.error){console.error(label,r.error);el.innerHTML=`<p class="muted">${label} list is temporarily unavailable.</p>`;continue}el.innerHTML=r.data?.length?r.data.map(x=>`<article class="card"><small>${label.toUpperCase()}</small><h2>${esc(x.title)}</h2><p>${esc(x.description||'')}</p><button class="btn" data-open-id="${esc(x.id)}">Open</button></article>`).join(''):'<p class="muted">Nothing published yet.</p>';el.querySelectorAll('[data-open-id]').forEach(b=>b.onclick=()=>{const path=label==='Course'?'course.html':label==='Project'?'project.html':'challenge.html';location.href=path+'?id='+encodeURIComponent(b.dataset.openId)})}}
async function profilePage(s){if(!$('#profileName'))return;if(!s){location.replace('login.html');return}const p=await getProfile(s);if(!p){toast('Your profile is not available yet. Please refresh.',true);return}$('#profileName').textContent=p.display_name||p.username||'Member';if($('#profileBio'))$('#profileBio').textContent=p.bio||'No bio yet.';if($('#profileDisplayName'))$('#profileDisplayName').value=p.display_name||'';if($('#profileBioInput'))$('#profileBioInput').value=p.bio||'';if($('#profileTags'))$('#profileTags').innerHTML=`<span class="tag level">⚙ ${esc((p.level||'initiate').toUpperCase())}</span><span class="tag position">🧭 ${esc((p.community_position||'member').toUpperCase())}</span>`;if($('#score'))$('#score').textContent=p.contribution_score??0;if($('#helped'))$('#helped').textContent=p.members_helped??0;const form=$('#profileUpdateForm');if(form&&!form.dataset.bound){form.dataset.bound='1';form.addEventListener('submit',async e=>{e.preventDefault();const name=form.elements.displayName.value.trim();if(!name)return toast('Display name is required.',true);busy(form,true,'Saving…');try{const r=await timeout(sb.from('profiles').update({display_name:name.slice(0,80),bio:form.elements.bio.value.trim().slice(0,500)}).eq('id',s.user.id).select().single());if(r.error)throw r.error;$('#profileName').textContent=r.data.display_name;$('#profileBio').textContent=r.data.bio||'No bio yet.';await refreshIdentity(s);toast('Profile updated successfully')}catch(err){console.error('profile update',err);toast(friendly(err),true)}finally{busy(form,false)}})}}
window.addEventListener('error',e=>console.error('Evolvian runtime error',e.error||e.message));window.addEventListener('unhandledrejection',e=>console.error('Evolvian promise error',e.reason));
document.addEventListener('DOMContentLoaded',async()=>{if(!init())return;bindAuth();let s=null;try{s=await authBoot()}catch(e){console.error('auth boot',e);toast('Account services could not initialize. Please refresh.',true)}try{await refreshIdentity(s);await post();await feed();await lists();await profilePage(s)}catch(e){console.error('page boot',e);toast('Some content could not load. Please refresh.',true)}});
})();