(()=>{if(window.__Evolvian_APP__)return;window.__Evolvian_APP__=1;
const $=(s,r=document)=>r.querySelector(s),esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};
const toast=(m,b=false)=>{let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=m;t.className='toast show'+(b?' bad':'');clearTimeout(t._timer);t._timer=setTimeout(()=>t.className='toast',4200)};
const friendly=e=>{const m=e?.message||String(e||'Unknown error');if(/invalid login credentials/i.test(m))return'Email or password is incorrect.';if(/email not confirmed/i.test(m))return'Please confirm your email before signing in.';if(/user already registered/i.test(m))return'This email is already registered. Sign in instead.';if(/database error saving new user/i.test(m))return'Account creation failed while saving your profile. Please try again.';if(/failed to fetch|networkerror|network request failed/i.test(m))return'Network connection failed. Check your internet connection and try again.';return m};
const withTimeout=(promise,ms=12000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out. Please check your connection and try again.')),ms))]);
let sb=null;
function init(){try{if(!window.supabase||!window.Evolvian_CONFIG?.SUPABASE_URL||!window.Evolvian_CONFIG?.SUPABASE_PUBLISHABLE_KEY)throw new Error('Authentication service is not configured.');sb=supabase.createClient(Evolvian_CONFIG.SUPABASE_URL,Evolvian_CONFIG.SUPABASE_PUBLISHABLE_KEY);window.EvolvianAuth=sb;return true}catch(e){console.error(e);toast('Authentication service could not start. Refresh the page.',true);return false}}
async function session(){if(!sb)return null;try{return(await withTimeout(sb.auth.getSession())).data.session}catch(e){console.error('getSession failed',e);return null}}
async function profile(s){if(!sb||!s)return null;try{const r=await withTimeout(sb.from('profiles').select('*').eq('id',s.user.id).maybeSingle());if(r.error){console.error('Profile read failed',r.error);return null}return r.data||null}catch(e){console.error('Profile read failed',e);return null}}
async function ensureProfile(s){return s?profile(s):null}
async function refreshIdentity(s){const current=s||await session();document.querySelectorAll('.avatar').forEach(a=>a.textContent='A');if(!current)return null;const p=await profile(current);document.querySelectorAll('.avatar').forEach(a=>{a.textContent=(p?.display_name||p?.username||current.user.email||'Member').trim().charAt(0).toUpperCase()||'M'});return p}
function setBusy(form,busy,label){const b=form?.querySelector('button[type="submit"],button:not([type])');if(!b)return;b.disabled=busy;b.dataset.originalText??=b.textContent;if(busy)b.textContent=label;else b.textContent=b.dataset.originalText}
function bindAuth(){const l=$('#loginForm');if(l){l.onsubmit=async e=>{e.preventDefault();if(!sb)return toast('Authentication service is unavailable. Refresh and try again.',true);const email=l.elements.email?.value.trim(),password=l.elements.password?.value||'';if(!email||!password)return toast('Enter your email and password.',true);setBusy(l,true,'Signing in…');try{const r=await withTimeout(sb.auth.signInWithPassword({email,password}));if(r.error)throw r.error;const p=await ensureProfile(r.data.session);if(!p)console.warn('Signed in but profile is not readable yet.');toast('Signed in successfully');setTimeout(()=>{location.href='index.html'},250)}catch(e){console.error('Login failed',e);toast(friendly(e),true);setBusy(l,false)}}}
const f=$('#signupForm');if(f){f.onsubmit=async e=>{e.preventDefault();if(!sb)return toast('Authentication service is unavailable. Refresh and try again.',true);const displayName=f.elements.displayName?.value.trim()||'Member',email=f.elements.email?.value.trim(),password=f.elements.password?.value||'';if(!email||!password)return toast('Enter your email and password.',true);if(displayName.length>80)return toast('Display name must be 80 characters or less.',true);if(password.length<6)return toast('Password must be at least 6 characters.',true);setBusy(f,true,'Creating account…');try{const r=await withTimeout(sb.auth.signUp({email,password,options:{data:{name:displayName,display_name:displayName}}}));if(r.error)throw r.error;if(r.data.session){await refreshIdentity(r.data.session);toast('Account created successfully');setTimeout(()=>location.href='profile.html',250)}else{setBusy(f,false);toast('Account created. Check your email to confirm, then sign in.');f.reset()}}catch(e){console.error('Signup failed',e);toast(friendly(e),true);setBusy(f,false)}}}}
async function boot(){if(!sb)return;const s=await session();await refreshIdentity(s);if($('#loginForm')&&s){location.href='index.html';return}document.querySelectorAll('[data-signout]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await withTimeout(sb.auth.signOut());if(r.error)throw r.error;location.href='login.html'}catch(e){b.disabled=false;toast(friendly(e),true)}});try{sb.auth.onAuthStateChange((event,ns)=>{setTimeout(()=>{if(event==='SIGNED_IN')refreshIdentity(ns);if(event==='SIGNED_OUT')document.querySelectorAll('.avatar').forEach(a=>a.textContent='A')},0)})}catch(e){console.error('Auth listener failed',e)}}
async function feed(){const el=$('#feed');if(!el||!sb)return;const r=await sb.from('posts').select('id,title,body,created_at,profiles(display_name,level,community_position)').order('created_at',{ascending:false}).limit(30);if(r.error)return el.innerHTML='<p class="muted">Feed unavailable. Please refresh.</p>';el.innerHTML=r.data?.length?r.data.map(p=>`<article class="post"><div class="posthead"><div class="mini">${esc((p.profiles?.display_name||'M')[0])}</div><div><b>${esc(p.profiles?.display_name||'Member')}</b><small>${esc((p.profiles?.level||'initiate').toUpperCase())} · ${esc((p.profiles?.community_position||'member').toUpperCase())}</small></div></div>${p.title?`<h2>${esc(p.title)}</h2>`:''}<p>${esc(p.body)}</p></article>`).join(''):'<p class="muted">No posts yet.</p>'}
async function post(){const f=$('#postForm');if(!f||!sb)return;f.onsubmit=async e=>{e.preventDefault();const s=await session();if(!s)return location.href='login.html';const r=await sb.from('posts').insert({author_id:s.user.id,type:'post',title:f.title.value.trim()||null,body:f.body.value.trim()});r.error?toast(friendly(r.error),true):(f.reset(),toast('Posted'),feed())}}
async function lists(){if(!sb)return;for(const [id,table,label] of [['courseList','courses','Course'],['projectList','projects','Project'],['challengeList','challenges','Challenge']]){const el=$('#'+id);if(!el)continue;const r=await sb.from(table).select('*').order('created_at',{ascending:false}).limit(30);el.innerHTML=r.error?`<p class="muted">${label} list unavailable.</p>`:r.data?.length?r.data.map(x=>`<article class="card"><small>${label.toUpperCase()}</small><h2>${esc(x.title)}</h2><p>${esc(x.description||'')}</p><button class="btn">Open</button></article>`).join(''):'<p class="muted">Nothing published yet.</p>'}}
async function profilePage(){const s=await session();if(!s){location.href='login.html';return}if($('#profileName')){const p=await ensureProfile(s);if(p){$('#profileName').textContent=p.display_name||p.username||'Member';if($('#profileBio'))$('#profileBio').textContent=p.bio||'No bio yet.';if($('#profileDisplayName'))$('#profileDisplayName').value=p.display_name||'';if($('#profileBioInput'))$('#profileBioInput').value=p.bio||'';if($('#profileTags'))$('#profileTags').innerHTML=`<span class="tag level">⚙ ${esc((p.level||'initiate').toUpperCase())}</span><span class="tag position">🧭 ${esc((p.community_position||'member').toUpperCase())}</span>`;if($('#score'))$('#score').textContent=p.contribution_score||0;if($('#helped'))$('#helped').textContent=p.members_helped||0}}const form=$('#profileUpdateForm');if(form)form.onsubmit=async e=>{e.preventDefault();const name=form.displayName.value.trim();if(!name)return toast('Display name is required.',true);setBusy(form,true,'Saving…');const r=await sb.from('profiles').update({display_name:name.slice(0,80),bio:form.bio.value.trim().slice(0,500),updated_at:new Date().toISOString()}).eq('id',s.user.id).select().single();setBusy(form,false);if(r.error)return toast(friendly(r.error),true);await refreshIdentity(s);if($('#profileName'))$('#profileName').textContent=r.data.display_name;if($('#profileBio'))$('#profileBio').textContent=r.data.bio||'No bio yet.';toast('Profile updated successfully')}}
window.addEventListener('error',e=>{console.error('Evolvian runtime error',e.error||e.message)});window.addEventListener('unhandledrejection',e=>console.error('Evolvian promise error',e.reason));
document.addEventListener('DOMContentLoaded',async()=>{if(!init())return;bindAuth();try{await boot()}catch(e){console.error('Boot failed',e);toast('Some account features could not initialize. Please refresh.',true)}try{await post();await feed();await lists();await profilePage()}catch(e){console.error('Page initialization failed',e)}});
})();