-- Evolvian Growth Engine
-- Run this migration in the connected Supabase project.
create table if not exists public.growth_requirements (
  id bigint generated by default as identity primary key,
  level_key text unique not null,
  level_name text not null,
  stage_order integer unique not null,
  min_points integer not null default 0,
  min_projects integer not null default 0,
  min_helped integer not null default 0,
  min_teaching integer not null default 0,
  min_answers integer not null default 0,
  min_consistency_days integer not null default 0,
  requires_review boolean not null default false,
  description text not null default '',
  created_at timestamptz not null default now()
);
insert into public.growth_requirements(level_key,level_name,stage_order,min_points,min_projects,min_helped,min_teaching,min_answers,min_consistency_days,requires_review,description) values
('initiate','Initiate',0,0,0,0,0,0,0,false,'Start learning, participate and build your first contribution.'),
('explorer','Explorer',1,50,1,0,0,1,7,false,'Explore paths, complete a first project and begin helping.'),
('builder','Builder',2,200,3,3,1,5,30,false,'Build consistently, publish useful work and contribute to others.'),
('mentor','Mentor',3,500,5,10,3,15,60,false,'Teach, answer questions and demonstrate reliable community impact.'),
('architect','Architect',4,1000,10,25,8,30,120,true,'Lead substantial work and help shape systems or learning.'),
('council','Council Member',5,2000,15,50,15,50,180,true,'Earned through sustained contribution, mentorship and trusted community review.')
on conflict(level_key) do update set level_name=excluded.level_name,stage_order=excluded.stage_order,min_points=excluded.min_points,min_projects=excluded.min_projects,min_helped=excluded.min_helped,min_teaching=excluded.min_teaching,min_answers=excluded.min_answers,min_consistency_days=excluded.min_consistency_days,requires_review=excluded.requires_review,description=excluded.description;
create table if not exists public.growth_events (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 event_type text not null,
 points integer not null default 0,
 source_id bigint,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create index if not exists growth_events_user_idx on public.growth_events(user_id,created_at desc);
alter table public.growth_requirements enable row level security;
alter table public.growth_events enable row level security;
drop policy if exists growth_requirements_read on public.growth_requirements;
create policy growth_requirements_read on public.growth_requirements for select to authenticated using (true);
drop policy if exists growth_events_own_read on public.growth_events;
create policy growth_events_own_read on public.growth_events for select to authenticated using (auth.uid()=user_id);
