-- Evolvian Growth Engine: verified activity tracking
-- Apply after 20261003_growth_engine.sql.
create or replace function public.record_growth_event(p_user_id uuid,p_event_type text,p_points integer,p_source_id bigint default null,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path = public, pg_temp as $$ begin if p_user_id is null or p_points is null or p_points <= 0 then return; end if; insert into public.growth_events(user_id,event_type,points,source_id,metadata) values(p_user_id,p_event_type,p_points,p_source_id,coalesce(p_metadata,'{}'::jsonb)); update public.profiles set contribution_score=coalesce(contribution_score,0)+p_points where id=p_user_id; end; $$;
create or replace function public.growth_from_post() returns trigger language plpgsql security definer set search_path = public, pg_temp as $$ declare pts integer; begin pts:=case when new.type='tutorial' then 15 when new.type='question' then 8 else 5 end; perform public.record_growth_event(new.author_id,'post_'||coalesce(new.type,'post'),pts,new.id,jsonb_build_object('post_type',new.type)); return new; end; $$;
drop trigger if exists trg_growth_post on public.posts; create trigger trg_growth_post after insert on public.posts for each row execute function public.growth_from_post();
create or replace function public.growth_from_comment() returns trigger language plpgsql security definer set search_path = public, pg_temp as $$ declare post_owner uuid; begin select author_id into post_owner from public.posts where id=new.post_id; perform public.record_growth_event(new.author_id,'answer_or_comment',3,new.id,jsonb_build_object('post_id',new.post_id)); if post_owner is not null and post_owner<>new.author_id then perform public.record_growth_event(post_owner,'community_engagement',1,new.id,jsonb_build_object('commenter_id',new.author_id)); end if; return new; end; $$;
drop trigger if exists trg_growth_comment on public.comments; create trigger trg_growth_comment after insert on public.comments for each row execute function public.growth_from_comment();
create or replace function public.growth_from_like() returns trigger language plpgsql security definer set search_path = public, pg_temp as $$ declare owner_id uuid; begin select author_id into owner_id from public.posts where id=new.post_id; if owner_id is not null and owner_id<>new.user_id then perform public.record_growth_event(owner_id,'post_received_like',1,new.post_id,jsonb_build_object('from_user',new.user_id)); end if; return new; end; $$;
drop trigger if exists trg_growth_like on public.post_likes; create trigger trg_growth_like after insert on public.post_likes for each row execute function public.growth_from_like();
create or replace function public.get_growth_snapshot(p_user_id uuid) returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$ declare points integer; projects integer:=0; helped integer; teaching integer; answers integer; consistency integer; stage integer:=0; req record; begin select coalesce(sum(points),0) into points from public.growth_events where user_id=p_user_id; select count(distinct author_id) into helped from public.comments c join public.posts p on p.id=c.post_id where p.author_id=p_user_id and c.author_id<>p.author_id; select count(*) into teaching from public.posts where author_id=p_user_id and type='tutorial'; select count(*) into answers from public.comments where author_id=p_user_id; select count(distinct created_at::date) into consistency from public.growth_events where user_id=p_user_id; for req in select * from public.growth_requirements order by stage_order loop if points>=req.min_points and projects>=req.min_projects and helped>=req.min_helped and teaching>=req.min_teaching and answers>=req.min_answers and consistency>=req.min_consistency_days then stage:=req.stage_order; end if; end loop; return jsonb_build_object('points',points,'projects',projects,'helped',helped,'teaching',teaching,'answers',answers,'consistency_days',consistency,'stage_order',stage); end; $$;
grant execute on function public.get_growth_snapshot(uuid) to authenticated;